disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Aman Thanvi"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "January 2, 2006"
  description = "Aman Thanvi's personal website"
  copyright = "© 2021-2025 Aman Thanvi"

[params.author]
  name = "Aman Thanvi"
  image = "images/profile.jpg"
  imageQuality = 100
  headline = "Cybersecurity Specialist | Federal Service"
  bio = "Cybersecurity Specialist with a Master of Engineering in Cybersecurity from the University of Maryland, College Park. Over six years of progressive cybersecurity experience within federal government and the private sector."
  links = [
    { github = "https://github.com/amanthanvi/" },
    { linkedin = "https://www.linkedin.com/in/amanthanvi/" }
  ]
