baseURL = "http://example.org/"
languageCode = "en-us"
title = "Aman Thanvi | @amanthanvi"
copyright = "© Copyright notice"
theme = "minima"
paginate = 7
googleAnalytics = ""
disqusShortname = "hugo-minima"

# Author has some of your information to be shown on the home 
# page of your blog.
[author]
name = "Aman Thanvi"
slogon = "CS + ACES Cybersecurity student @ University of Maryland, College Park 🐢"

# Params.social is an array containing your social network accounts,
# Each has a lowercase name, a svg formatted icon and a url to the 
# webpage of your account. They will be shown at the bottom of every
# page of your blog. 
# Be sure the svgs you select to use must have both the width and the
# height set 18. If you don't wanna put the svg code in this config
# file, you can instead save them to the `data/svg.toml` file under 
# the root directory of your blog using a format like `name = '<svg>'`
[[params.social]]
name = "github"  
url = "https://github.com/amanthanvi"
svg = ""
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/amanthanvi/"
svg = ""

# Menu.main is an array that's used to decide what entries can be shown
# on the navigator of yur blog. You can use a weight to make them ordered.
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 2
[[menu.main]]
name = "Projects"
url = "/projects"
weight = 3

# You can classify your posts by setting taxanomies in the front matter like
# categories = ["apple", "banana"]
# series = ["s1", "s2"]
# tags = ["t1", "t2"]
# A little suggestion: one post belongs to one series, one category and multiple tags.
[taxonomies]
category = "categories"
tag = "tags"
series = "series"


# Make sure all the codes in a post are highlighted correctly
# so better not edit this.
[markup.highlight]
lineNos = true
noClasses = false
